spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tresshop
    username: root
    password: abhi@Nov11
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 20000
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    open-in-view: false


server:
  port: 9090
  servlet:
    contextPath: /tresshop/api/v1
  http2:
    enabled: true
  tomcat:
    max-threads: 200

#
#logging:
#  config: classpath:logback-spring.xml
#  levels:
#    com.ril.payment.engine.web: DEBUG
#    org:
#      springframework: INFO
#      apache:
#        http: DEBUG
#  appenders:
#    name: rollingfile
#    rollingfile:
#      directory: /opt/apps/payment-engine/PE-tomcat/logs
#      prefix: payment-engine


rest:
  url:
    paytm:
      mid: OAJI1168155660467601
      web-site: WEBSTAGING
      app-site: WEBSTAGING
      industry-type: Retail
      m-key: rd!xZC0grzGSBaTG
      template-name: paytm
      transaction: https://securegw-stage.paytm.in/theia/processTransaction
      callback: https://payment-uat.services.ajio.com/payment-engine/api/v1/b2b-callback/paytm/
      transaction-status: https://securegw-stage.paytm.in/order/status
      refund-against-payment: https://securegw-stage.paytm.in/refund/api/v1/async/refund
      connection-timeout: 35000
      read-timeout: 35000
      refund:
        client-id: C11
        version: v1
    bill-desk:
      mid: RILTST
      user-id: riltst
      checksum-key: LO9eurhPwb1X
      template-name: billdesk
      initiation: https://www.billdesk.com/pgidsk/PGIDirectRequest?reqid=BDRDF011
      re-initiation: https://www.billdesk.com/pgidsk/PGIDirectRequest?reqid=BDRDF001
      net-banking-wallet: https://www.billdesk.com/pgidsk/PGIDirectRequest?reqid=BDRDF003
      upi-payment: https://www.billdesk.com/pgidsk/PGIDirectRequest?reqid=BDRDF007
      authorize: https://www.billdesk.com/pgidsk/PGIDirectRequest?reqid=BDRDF002
      query: https://www.billdesk.com/pgidsk/PGIQueryController
      refund: https://www.billdesk.com/pgidsk/PGIRefundController
      s2s-sla: 300000
      connection-timeout: 35000
      read-timeout: 35000
      callback:
        s2s: https://payment-uat.services.ajio.com/payment-engine/api/v1/callback/billdesk
        card: https://payment-uat.services.ajio.com/payment-engine/api/v1/b2b-callback/billdesk/card/
        upi: https://payment-uat.services.ajio.com/payment-engine/api/v1/callback/billdesk
        net-banking-wallet: https://payment-uat.services.ajio.com/payment-engine/api/v1/b2b-callback/billdesk/banking/


    razorpay:
      create-order: https://prod-api-static.razorpay.com/v1/orders
      validate-authentication-type: https://prod-api-static.razorpay.com/v1/payment/flows
      make-payment: https://prod-api-static.razorpay.com/v1/payments/create/redirect/
      resend-otp: https://prod-api-static.razorpay.com/v1/payments/{razorpay-payment-id}/otp/resend
      submit-otp-s2s: https://prod-api-static.razorpay.com/v1/payments/{razorpay-payment-id}/otp/submit
      make-payment-upi-s2s: https://prod-api-static.razorpay.com/v1/payments/create/upi
      enquire-against-order: https://prod-api-static.razorpay.com/v1/orders/{order-id}/payments
      refund-against-payment:  https://prod-api-static.razorpay.com/v1/payments/{razorpay-payment-id}/refund
      card-details-for-payment: https://prod-api-static.razorpay.com/v1/payments/{razorpay-payment-id}/card
      s2s-sla: 300000
      connection-timeout: 10000
      read-timeout: 10000
      callback:
        b2b: https://payment-uat.services.ajio.com/payment-engine/api/v1/b2b-callback/razorpay/b2b/{order-id}



credentials:
  razorpay:
    username: ENC(0C9F6F8CBB3450AD0133B0CBD7E697F373978D308524B97158BBCE4111FE49A5)
    password: ENC(4418CC9103AB89CE0D4688050998D7D6E00FA2B6680047F593ECA9649282CD409BBD64AA27A4BF0E)

#    username: rzp_test_8bORemK76nsRz7
#    password: aTP6Gw1tp74h0Pmez4tmnkdo



secure:
  mac: iH@McQfTjWnZr4t7w!z%C*F@JaNdRgUk


