DROP TABLE IF EXISTS rewards; 
CREATE TABLE rewards  (
	reward_id VARCHAR(100) NOT NULL,
	status VARCHAR(50) NOT NULL,
	cust_id VARCHAR(100) NOT NULL,
	type VARCHAR(50) NOT NULL,
	description VARCHAR(500),
	creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
PRIMARY KEY( reward_id )
);
