DROP TABLE IF EXISTS rewards;
CREATE TABLE rewards  (
	reward_id VARCHAR(100) NOT NULL,
	status VARCHAR(50) NOT NULL,
	customer_id VARCHAR(100) NOT NULL,
	type VARCHAR(50) NOT NULL,
	description VARCHAR(500),
	created_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	lastUpdated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
PRIMARY KEY( reward_id )
);
