DROP TABLE IF EXISTS sellers;
CREATE TABLE sellers (
	seller_id  VARCHAR(500) NOT NULL,
	password VARCHAR(500) NOT NULL,
	email_id VARCHAR(500) NOT NULL,
	phone_number BIGINT NOT NULL,
	vendor_id VARCHAR(100) NOT NULL,
	TIN VARCHAR(500),
	points INT,
	creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
PRIMARY KEY ( seller_id )
);
