DROP TABLE IF EXISTS sellers;
CREATE TABLE sellers (
	user_full_name VARCHAR(200) NOT NULL,
	password VARCHAR(50) NOT NULL,
	email_id VARCHAR(200) NOT NULL,
	phone_number VARCHAR(13) NOT NULL,
	countryID VARCHAR(2) NOT NULL,
	regionID VARCHAR(2) NOT NULL,
	vendor_ids VARCHAR(1000) NOT NULL,
	status BOOLEAN NOT NULL,
	TIN VARCHAR(100),
	creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
PRIMARY KEY ( phone_number )
);
