DROP TABLE IF EXISTS system_banners;
CREATE TABLE system_banners (
	banner_id INT(10) NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	description VARCHAR(500) NOT NULL,
	title VARCHAR(200) ,
	short_description VARCHAR(500) ,
	type VARCHAR(50) NOT NULL,
	start_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	end_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	image_url VARCHAR(100),
	created_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	last_Updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
PRIMARY KEY( banner_id, start_date, end_date )
);
