spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tresshop
    username: root
    password: abhi@Nov11
#    driver-class-name: oracle.jdbc.driver.M
    hikari:
      maximum-pool-size: 10
      connection-timeout: 20000
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    open-in-view: false


server:
  port: 9090
  servlet:
    contextPath: /payment-engine/api/v1
  http2:
    enabled: true
  tomcat:
    max-threads: 200

#
#logging:
#  config: classpath:logback-spring.xml
#  levels:
#    com.ril.payment.engine.web: DEBUG
#    org:
#      springframework: INFO
#      apache:
#        http: DEBUG
#  appenders:
#    name: rollingfile
#    rollingfile:
#      directory: /opt/apps/payment-engine/PE-tomcat/logs
#      prefix: payment-engine