jasypt:
  encryptor:
    algorithm: PBEWITHSHA1ANDDESEDE
    stringOutputType: hexadecimal
    bean: encryptorBean
    providerName: SunJCE
    password: ${JASYPT_PASSWORD}

spring:
  datasource:
    url: ENC(9D24CBF9AF44B80D0258CCB21AB99E587411A143D757E7E73E7DAF8F400CB30BBBD196C7255D29A4D6121B241CD6E6711EB1CA0C7004C14EEB5C7CBDDD64323D1D7DCB148F67E8994D3EE9EBA4201E7C)
    username: ENC(4DAB468CFAF6B64E56AB48E029D65C35)
    password: ENC(8B7EEE42ABF06C3EDDB30BCA02510689)
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      maximum-pool-size: 111
      connection-timeout: 20000
      minimum-idle: 31
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true


  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
    show-sql: false
    open-in-view: false


server:
  port: 9090
  servlet:
    contextPath: /payment-engine/api/v1
  http2:
    enabled: true
  tomcat:
    max-threads: 200


logging:
  config: classpath:logback-spring.xml
  levels:
    com.ril.payment.engine.web: DEBUG
    org:
      springframework: INFO
      apache:
        http: DEBUG
  appenders:
    name: rollingfile
    rollingfile:
      directory: /opt/paymentengine/logs
      prefix: payment-engine


rest:
  url:
    paytm:
      mid: ENC(F001B5D17E78034BB3071C3616CB7315918E1D1C26A417B9A5B4647580F3C071)
      web-site: ReliANWEB
      app-site: ReliANWAP
      industry-type: Retail92
      m-key: ENC(1692BBA6CF1426B4089686DA42D2B6105146E0FC921441D1EAC988C37FBCE6D3)
      template-name: paytm
      transaction: https://securegw.paytm.in/order/process
      callback: https://payment.services.ajio.com/payment-engine/api/v1/b2b-callback/paytm/
      transaction-status: https://securegw.paytm.in/order/status
      refund-against-payment:  https://securegw.paytm.in/refund/apply
      connection-timeout: 35000
      read-timeout: 35000
      refund:
        client-id: C11
        version: v1
    bill-desk:
      mid: ENC(1D549577553A42658D4B81EC043865BB576427CF98609682)
      user-id: ENC(632655D0617C5F9B32845E4A8E4BE745685B0A018196507E)
      checksum-key: ENC(D2AB8E44EC5F90982A8D9A9BBCB337B48FB0C63520856E68)
      template-name: billdesk
      initiation: https://www.billdesk.com/pgidsk/PGIDirectRequest?reqid=BDRDF011
      re-initiation: https://www.billdesk.com/pgidsk/PGIDirectRequest?reqid=BDRDF001
      net-banking-wallet: https://www.billdesk.com/pgidsk/PGIDirectRequest?reqid=BDRDF003
      upi-payment: https://www.billdesk.com/pgidsk/PGIDirectRequest?reqid=BDRDF007
      authorize: https://www.billdesk.com/pgidsk/PGIDirectRequest?reqid=BDRDF002
      query: https://www.billdesk.com/pgidsk/PGIQueryController
      refund: https://www.billdesk.com/pgidsk/PGIRefundController
      s2s-sla: 300000
      connection-timeout: 35000
      read-timeout: 35000
      callback:
        s2s: https://payment.services.ajio.com/payment-engine/api/v1/callback/billdesk
        card: https://payment.services.ajio.com/payment-engine/api/v1/b2b-callback/billdesk/card/
        upi: https://payment.services.ajio.com/payment-engine/api/v1/callback/billdesk
        net-banking-wallet: https://payment.services.ajio.com/payment-engine/api/v1/b2b-callback/billdesk/banking/


    razorpay:
      create-order: https://prod-api-static.razorpay.com/v1/orders
      validate-authentication-type: https://prod-api-static.razorpay.com/v1/payment/flows
      make-payment: https://prod-api-static.razorpay.com/v1/payments/create/redirect/
      resend-otp: https://prod-api-static.razorpay.com/v1/payments/{razorpay-payment-id}/otp/resend
      submit-otp-s2s: https://prod-api-static.razorpay.com/v1/payments/{razorpay-payment-id}/otp/submit
      make-payment-upi-s2s: https://prod-api-static.razorpay.com/v1/payments/create/upi
      enquire-against-order: https://prod-api-static.razorpay.com/v1/orders/{order-id}/payments
      refund-against-payment:  https://prod-api-static.razorpay.com/v1/payments/{razorpay-payment-id}/refund
      card-details-for-payment: https://prod-api-static.razorpay.com/v1/payments/{razorpay-payment-id}/card
      s2s-sla: 300000
      connection-timeout: 10000
      read-timeout: 10000
      callback:
        b2b: https://payment.services.ajio.com/payment-engine/api/v1/b2b-callback/razorpay/b2b/{order-id}


    hybris:
      client-id: ENC(D5A43CC5D6B15DC608F494292A69DF9D518F617576354370)
      client-secret: ENC(5515E48619C3087A8E6475DC1C25D143)
      grant-type: client_credentials
      refresh-grant-type: client_credentials
      auth-token-retry-limit: 1
      auth-token-call-count: 0
      auth-token: https://www.ajio.com/rilfnlwebservices/oauth/token
      price-calculate: https://www.ajio.com/rilfnlwebservices/v2/rilfnl//payment/priceCalculation
      fraud-check: https://www.ajio.com/rilfnlwebservices/v2/rilfnl/payment/fraudCheck
      send-otp: https://www.ajio.com/rilfnlwebservices/v2/rilfnl/kiosk/sendOTP
      validate-otp: https://www.ajio.com/rilfnlwebservices/v2/rilfnl/login/verifyOTP
      revalidate-otp: https://www.ajio.com/rilfnlwebservices/v2/rilfnl/payment/otpValidated
      bill-desk:
        transaction-not-found: https://www.ajio.com/rilfnlwebservices/v2/rilfnl/updatePaymentDetails
      razorpay:
        transaction-not-found: https://www.ajio.com/rilfnlwebservices/v2/rilfnl/updateRazorPayPayment
      connection-timeout: 15000
      read-timeout: 15000

    ajio-cash:
      login: https://ajiowallet.services.ajio.com/ajiocash/auth/login
      cart-benefit: https://ajiowallet.services.ajio.com/ajiocash/benefit/cartBenefit
      earn: https://ajiowallet.services.ajio.com/ajiocash/v1/order/payments
      refresh-token: https://ajiowallet.services.ajio.com/ajiocash/auth/refreshtoken
      refund: https://ajiowallet.services.ajio.com/v1/order/processRefund
      undo-burn: https://ajiowallet.services.ajio.com/ajiocash/v1/order/undoPayments
      fetch-wallet: https://ajiowallet.services.ajio.com/ajiocash/wallet/userWallet
      username: ENC(B3BBD4DE13DB18EF95C16A7E63DE645B614184A395E4C123)
      password: ENC(4ACE5EBA8244CCB3FE351DB02F17F6F405FEBB206D8D7824)
      tenant: AJIO
      connection-timeout: 6000
      read-timeout: 6000

    s2s:
      connection-timeout: 5000
      read-timeout: 5000

##### Jio Prime points ###########
jio:
  prime:
    get-active-balance-url: http://10.21.79.38:8080/rcs/prime-point/getActualPoint
    redeem-active-points-url: http://10.21.79.38:8080/rcs/prime-point/redeemActivePoints
    check-user-exist-url: http://10.21.79.38:8080/rcs/prime-point/checkPrimeUser
    add-prime-user-url: http://10.21.79.38:8080/rcs/prime-point/addPrimeUser
    credit-points-url: http://10.21.79.38:8080/rcs/prime-point/addPendingPoint
    refund-redeemed-points-url: http://10.21.79.38:8080/rcs/prime-point/addActivePoints


credentials:
  razorpay:
    username: ENC(7BB0B5CF6416C3237669C31CE37AF5448A7902A16C333B45760177BC4779E0BB)
    password: ENC(CF7E10154BA9D163D40D3C54DF196D9FA03C2DBF071BA3DEB37919C87177EB508EA8AAE0109FB118)



secure:
  mac: ENC(D97E6C0A879ECAFD7E5B400134ADE386CF0709343740640FA98D62A69592138557D45F6A6145E68C)

kms:
  timeout:
    read: 5000
    connection: 5000
  tenant: ENC(81AD76EC566F921899545979E93C370F3C053B009C9014449C3C669659F3E281)
  login:
    username: ENC(0B6C6A9B37AD723CCA431497E40DEB68100EE305E9BE0404)
    password: ENC(066342E31D43877CD5E53D2EE4220F4BE42920D7227533B8B3018EDE1532C7881D8BA037E86D2B2C7D5C7AC778F51B55B350D41B442ED786C4B623F89E4F3E6C53561318B1E5EEDAC700E1B40195A9C4)
    auth:
      url: auth/login
  refresh:
    token:
      url: auth/refreshtoken
  base:
    url: https://kms.services.ajio.com/kms/

event:
  expire-record-limit: 3

filter:
  base:
    url-patterns: /authorization/*, /cache/*, /jpp/*, /payment/*, /user/*, /service/*

payment:
  checksum-key: ENC(8816AEF484896234DC2B393DB8F1BF04D373AB76C3D6841AF4F95CB9429D4A46D1C4E1FA73100763)
  transaction-not-found:
    update-hybris: true