jasypt:
  encryptor:
    algorithm: PBEWITHSHA1ANDDESEDE
    stringOutputType: hexadecimal
    bean: encryptorBean
    providerName: SunJCE
    password: ${JASYPT_PASSWORD}


server:
  port: 9099
  servlet:
    contextPath: /payment-engine-batch/api/v1

spring:
  datasource:
    url: ENC(DC481D2DA50C6B4B4A2EF1EA68BD5C790E8BDF28275C0140C3C42250E25A67A43FD4F2A3C0133DDB175B856902BD980F7433AE051F9B68D1)
    username: ENC(76410BC895E11A2611998CCF40D30255A52A5D0A788AE28E)
    password: ENC(A7011F0FA2C0FF42DB76DB6BC86F6E6D36CB7EEBAD2DCDC3706A237D7A8E085C)
    driverClassName: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate.ddl-auto: update
    show-sql: false
    generate-ddl: true
  properties:
    hibernate.format_sql: true
    hibernate.enable_lazy_load_no_trans: true
    org.hibernate.envers.audit_table_suffix: _activity
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2
  batch:
    job:
      enabled: false
    chunk:
      size: 51
    adonp:
      chunk:
        size: 1
    event-status:
      not-to-query: SUCCESS,INVALID
    s2s-event-status:
      not-to-query: SUCCESS,INVALID
      record-consider-in-minute: 5
    transaction-status:
      query: PENDING, ABORTED

logging:
  config: classpath:logback-spring.xml
  levels:
    org.springframework: INFO
    com.ril.service.batch: INFO
    org.hibernate.SQL: INFO
  appenders:
    name: rollingfile
    rollingfile:
      directory: /home/nodeadm/opt/logs
      prefix: pe-batch

expiring:
  alert:
    adonp:
      cycle: 1440
    payment-transaction:
      cycle: 30
    event-handler:
      cycle: 30
    s2s-event-handler:
      cycle: 10

activation:
  cycle: 2
expired:
  cycle: 2
recently:
  updated:
    cycle: 20
promo:
  active:
    cycle: 2
  expire:
    cycle: 2

process-burn:
  cycle: 5

maxAttempts: 3
backOffDelay: 20

template:
  sms:
    expiring: 123
    expired: expired
    activate: activated
  email:
    expiring: expiringMail
    expired: expiredMail
    activate: activatedMail

batch:
  initialize-schema: never
  initializer:
    enabled: false

rest:
  event:
    url: http://10.129.80.124:9090/payment-engine/api/v1/event/process
  processTransaction:
    url: http://10.129.80.124:9090/payment-engine/api/v1/transaction/pending/process


mail:

  smtp:
    server: 10.129.79.250
    starttls:
      enable: true
    connection-timeout: 5000
    timeout: 5000
    write-timeout: 5000
  transport:
    protocol: smtp

report:
  adonp:
    error-not-in-query: ABORTED,PAYMENT_GATEWAY_EXCEPTION

  file:
    location: /home/nodeadm/opt/
    name: reporting.xls
    adonp-report-name: ADONP_REPORT
    purchase-transaction-report-name: PURCHASE_TRANSACTION_REPORT
    zip:
      location: /home/nodeadm/opt/
      name: reporting.zip
  input-date-string: 01-08-2019


#==============================================================
  # Do not modify these details otherwise quartz will hv problem
  #to read these data
  #Configure Main Scheduler Properties
#==============================================================
org.quartz.scheduler.instanceName : PaymentEngineScheduler
org.quartz.scheduler.instanceId : AUTO
#==============================================================
  #Configure ThreadPool
#==============================================================
org.quartz.threadPool.class : org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.makeThreadsDaemons : true
org.quartz.threadPool.threadCount: 11
#==============================================================
  #Configure JobStore
#==============================================================
org.quartz.jobStore.misfireThreshold : 60000
org.quartz.jobStore.class : org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.driverDelegateClass : org.quartz.impl.jdbcjobstore.oracle.OracleDelegate
org.quartz.jobStore.tablePrefix : QRTZ_
org.quartz.jobStore.dataSource : myDS
org.quartz.jobStore.isClustered : true
org.quartz.jobStore.clusterCheckinInterval : 20000
#==============================================================
  #Non-Managed Configure Datasource
#==============================================================
org.quartz.dataSource.myDS.driver : oracle.jdbc.OracleDriver
org.quartz.dataSource.myDS.URL : jdbc:oracle:thin:@//10.129.34.183:1521/PMTSRVDB
org.quartz.dataSource.myDS.user : paymentservice
org.quartz.dataSource.myDS.password : rilpaymentservice
org.quartz.dataSource.myDS.maxConnections : 11
org.quartz.dataSource.myDS.validationQuery : select 0 from dual
org.quartz.plugin.shutdownHook.class: org.quartz.plugins.management.ShutdownHookPlugin
org.quartz.plugin.shutdownHook.cleanShutdown: true

